// Generated by `supabase gen types typescript` (via MCP). Regenerate after schema
// changes — see supabase/README.md. Do not edit by hand.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      competition_scores: {
        Row: {
          competition_id: string
          created_at: string
          event_id: string
          id: string
          notes: string
          placement: number | null
          points: number | null
          recorded_by: string | null
          team_id: string
        }
        Insert: {
          competition_id: string
          created_at?: string
          event_id: string
          id?: string
          notes?: string
          placement?: number | null
          points?: number | null
          recorded_by?: string | null
          team_id: string
        }
        Update: {
          competition_id?: string
          created_at?: string
          event_id?: string
          id?: string
          notes?: string
          placement?: number | null
          points?: number | null
          recorded_by?: string | null
          team_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "competition_scores_competition_id_fkey"
            columns: ["competition_id"]
            isOneToOne: false
            referencedRelation: "competitions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "competition_scores_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "events"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "competition_scores_recorded_by_fkey"
            columns: ["recorded_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "competition_scores_team_id_fkey"
            columns: ["team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
        ]
      }
      competitions: {
        Row: {
          created_at: string
          division: Database["public"]["Enums"]["division_code"]
          held_on: string | null
          id: string
          location: string
          name: string
        }
        Insert: {
          created_at?: string
          division: Database["public"]["Enums"]["division_code"]
          held_on?: string | null
          id?: string
          location?: string
          name: string
        }
        Update: {
          created_at?: string
          division?: Database["public"]["Enums"]["division_code"]
          held_on?: string | null
          id?: string
          location?: string
          name?: string
        }
        Relationships: []
      }
      events: {
        Row: {
          division: Database["public"]["Enums"]["division_code"]
          id: string
          name: string
        }
        Insert: {
          division: Database["public"]["Enums"]["division_code"]
          id?: string
          name: string
        }
        Update: {
          division?: Database["public"]["Enums"]["division_code"]
          id?: string
          name?: string
        }
        Relationships: []
      }
      pairings: {
        Row: {
          created_at: string
          event_id: string
          id: string
          student1_id: string
          student2_id: string | null
          student3_id: string | null
          team_id: string
        }
        Insert: {
          created_at?: string
          event_id: string
          id?: string
          student1_id: string
          student2_id?: string | null
          student3_id?: string | null
          team_id: string
        }
        Update: {
          created_at?: string
          event_id?: string
          id?: string
          student1_id?: string
          student2_id?: string | null
          student3_id?: string | null
          team_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "pairings_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "events"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pairings_student1_id_fkey"
            columns: ["student1_id"]
            isOneToOne: false
            referencedRelation: "students"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pairings_student2_id_fkey"
            columns: ["student2_id"]
            isOneToOne: false
            referencedRelation: "students"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pairings_student3_id_fkey"
            columns: ["student3_id"]
            isOneToOne: false
            referencedRelation: "students"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pairings_team_id_fkey"
            columns: ["team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
        ]
      }
      practice_scores: {
        Row: {
          created_at: string
          id: string
          max_score: number | null
          notes: string
          pairing_id: string
          placement: number | null
          raw_score: number | null
          recorded_by: string | null
          taken_on: string
        }
        Insert: {
          created_at?: string
          id?: string
          max_score?: number | null
          notes?: string
          pairing_id: string
          placement?: number | null
          raw_score?: number | null
          recorded_by?: string | null
          taken_on?: string
        }
        Update: {
          created_at?: string
          id?: string
          max_score?: number | null
          notes?: string
          pairing_id?: string
          placement?: number | null
          raw_score?: number | null
          recorded_by?: string | null
          taken_on?: string
        }
        Relationships: [
          {
            foreignKeyName: "practice_scores_pairing_id_fkey"
            columns: ["pairing_id"]
            isOneToOne: false
            referencedRelation: "pairings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "practice_scores_recorded_by_fkey"
            columns: ["recorded_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          created_at: string
          full_name: string
          id: string
          role: Database["public"]["Enums"]["app_role"]
        }
        Insert: {
          created_at?: string
          full_name?: string
          id: string
          role?: Database["public"]["Enums"]["app_role"]
        }
        Update: {
          created_at?: string
          full_name?: string
          id?: string
          role?: Database["public"]["Enums"]["app_role"]
        }
        Relationships: []
      }
      students: {
        Row: {
          created_at: string
          division: Database["public"]["Enums"]["division_code"]
          full_name: string
          grad_year: number | null
          id: string
          notes: string
        }
        Insert: {
          created_at?: string
          division: Database["public"]["Enums"]["division_code"]
          full_name: string
          grad_year?: number | null
          id?: string
          notes?: string
        }
        Update: {
          created_at?: string
          division?: Database["public"]["Enums"]["division_code"]
          full_name?: string
          grad_year?: number | null
          id?: string
          notes?: string
        }
        Relationships: []
      }
      team_members: {
        Row: {
          student_id: string
          team_id: string
        }
        Insert: {
          student_id: string
          team_id: string
        }
        Update: {
          student_id?: string
          team_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "team_members_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "students"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "team_members_team_id_fkey"
            columns: ["team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
        ]
      }
      teams: {
        Row: {
          capacity: number
          code: string
          created_at: string
          division: Database["public"]["Enums"]["division_code"]
          id: string
          name: string
        }
        Insert: {
          capacity?: number
          code: string
          created_at?: string
          division: Database["public"]["Enums"]["division_code"]
          id?: string
          name: string
        }
        Update: {
          capacity?: number
          code?: string
          created_at?: string
          division?: Database["public"]["Enums"]["division_code"]
          id?: string
          name?: string
        }
        Relationships: []
      }
      test_bank_links: {
        Row: {
          added_by: string | null
          created_at: string
          division: Database["public"]["Enums"]["division_code"]
          event_id: string | null
          id: string
          source: string
          title: string
          url: string
        }
        Insert: {
          added_by?: string | null
          created_at?: string
          division: Database["public"]["Enums"]["division_code"]
          event_id?: string | null
          id?: string
          source?: string
          title: string
          url: string
        }
        Update: {
          added_by?: string | null
          created_at?: string
          division?: Database["public"]["Enums"]["division_code"]
          event_id?: string | null
          id?: string
          source?: string
          title?: string
          url?: string
        }
        Relationships: [
          {
            foreignKeyName: "test_bank_links_added_by_fkey"
            columns: ["added_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "test_bank_links_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "events"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      app_role: "captain" | "coach" | "admin"
      division_code: "B" | "C"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      app_role: ["captain", "coach", "admin"],
      division_code: ["B", "C"],
    },
  },
} as const
