-- Seed the official 2026 Science Olympiad event lineup (23 events per division).
-- Source: soinc.org/division-b-events and /division-c-events.
-- Names are stored without a "- Div C" suffix; the division column carries that.
-- Idempotent: safe to re-run.

insert into public.events (division, name) values
  ('B', 'Dynamic Planet'),
  ('B', 'Meteorology'),
  ('B', 'Remote Sensing'),
  ('B', 'Rocks and Minerals'),
  ('B', 'Solar System'),
  ('B', 'Codebusters'),
  ('B', 'Experimental Design'),
  ('B', 'Ping-Pong Parachute'),
  ('B', 'Write It Do It'),
  ('B', 'Anatomy and Physiology'),
  ('B', 'Disease Detectives'),
  ('B', 'Botany'),
  ('B', 'Heredity'),
  ('B', 'Water Quality'),
  ('B', 'Crime Busters'),
  ('B', 'Food Science'),
  ('B', 'Hovercraft'),
  ('B', 'Circuit Lab'),
  ('B', 'Thermodynamics'),
  ('B', 'Roller Coaster'),
  ('B', 'Boomilever'),
  ('B', 'Elastic Launched Gliders'),
  ('B', 'Scrambler'),
  ('C', 'Astronomy'),
  ('C', 'Dynamic Planet'),
  ('C', 'Remote Sensing'),
  ('C', 'Rocks and Minerals'),
  ('C', 'Codebusters'),
  ('C', 'Engineering CAD'),
  ('C', 'Experimental Design'),
  ('C', 'Ping-Pong Parachute'),
  ('C', 'Anatomy and Physiology'),
  ('C', 'Disease Detectives'),
  ('C', 'Botany'),
  ('C', 'Designer Genes'),
  ('C', 'Water Quality'),
  ('C', 'Chemistry Lab'),
  ('C', 'Forensics'),
  ('C', 'Protein Modeling'),
  ('C', 'Hovercraft'),
  ('C', 'Circuit Lab'),
  ('C', 'Thermodynamics'),
  ('C', 'Electric Vehicle'),
  ('C', 'Boomilever'),
  ('C', 'Electric Wright Stuff'),
  ('C', 'Mission Possible')
on conflict (division, name) do nothing;
